In [123]:
import numpy as np

In [124]:
#3a
#могу так
def polyregression1(x, y, n):
    return np.array(list(reversed(np.polyfit(x, y, n))))

In [125]:
#чуть больше самостоятельности -- минимизация суммы квадратов это минимизация нормы ||ga - y||^2 по а
#минимизируем встроенной штукой
def polyregression2(x, y, n):
    m = len(x)
    g = np.zeros([m, n + 1])
    for i in range(m):
        g[i][0] = 1
        for j in range(n):
            g[i][j + 1] = g[i][j] * x[i]
    return np.linalg.lstsq(g, y, rcond=None)[0]

In [126]:
# а еще мы знаем где минимум достигается (aT * a * x = aT * b), поэтому сами посчитаем
# можно вместо solve вызвать обратную матрицу, но не очень принципиально
def polyregression3(x, y, n):
    m = len(x)
    g = np.zeros([m, n + 1])
    for i in range(m):
        g[i][0] = 1
        for j in range(n):
            g[i][j + 1] = g[i][j] * x[i]
    return np.linalg.solve(np.matmul(np.transpose(g), g), np.matmul(np.transpose(g), y))

In [127]:
u = np.array([0.0, 1.0, 2.0, 3.0,  4.0,  5.0])
v = np.array([0.0, 0.8, 0.9, 0.1, -0.8, -1.0])
deg = 3
print(polyregression1(u, v, deg))
print(polyregression2(u, v, deg))
print(polyregression3(u, v, deg))

[-0.03968254  1.69312169 -0.81349206  0.08703704]
[-0.03968254  1.69312169 -0.81349206  0.08703704]
[-0.03968254  1.69312169 -0.81349206  0.08703704]


In [128]:
#3b
from numpy import *
from scipy import optimize

x = np.array([36, 36, 19, 18, 33, 26])
y = np.array([14, 10, 28, 31, 18, 26])
#возвращаем массив расстояний до центра окружности
def list_of_distances_from_all_points(pnt):
    return sqrt((x - pnt[0]) ** 2 + (y - pnt[1]) ** 2)

#если центр задан, то искомый радиус -- среднее расстояние до точки от центра
#возвращаем массив расстояний до оптимальной окружности с заданным центром
def distances_to_circle(center):
    distances = list_of_distances_from_all_points(center)
    return distances - distances.mean()

def solution():
    #первое приближение оптимального центра
    xs = x.mean()
    ys = y.mean()
    start = xs, ys
    #хотим минимизировать сумму квадратов того, что возвращает 'distances_to_circle', это и делает leastsq
    (xopt, yopt), _ = optimize.leastsq(distances_to_circle, start)
    point_opt = np.array([xopt, yopt])
    radius_opt = list_of_distances_from_all_points(point_opt).mean()
    return (point_opt, radius_opt)
    

In [129]:
print(solution())

(array([9.88759499, 3.6875234 ]), 27.35040767420324)
